import { query } from "../index.js";

const sampleOffenses = [
  {
    id: "speeding-excess",
    name: "Exceeding Speed Limit",
    aliases: ["overspeeding", "speeding", "excess speed", "over speed limit"],
    description: "Driving a motor vehicle at a speed exceeding the prescribed speed limit for that road or area.",
    category: "speeding-reckless",
    severity: "minor",
    citation: "Traffic Act Cap 403, Section 44",
    act: "Traffic Act Cap 403",
    section: "Section 44",
    min_fine: 500,
    max_fine: 5000,
    max_imprisonment: null,
    course_of_action: "The officer may issue a charge sheet (P.B. Form). Do not pay on the spot. Plead guilty or appear in court on the date specified in the charge sheet if you wish to contest.",
    law_version: "2024",
  },
  {
    id: "dangerous-driving",
    name: "Dangerous Driving",
    aliases: ["reckless driving", "careless driving", "dangerous operation"],
    description: "Driving a motor vehicle in a manner that is dangerous to the public, having regard to all the circumstances of the case.",
    category: "speeding-reckless",
    severity: "serious",
    citation: "Traffic Act Cap 403, Section 46",
    act: "Traffic Act Cap 403",
    section: "Section 46",
    min_fine: 50000,
    max_fine: 100000,
    max_imprisonment: "2 years",
    course_of_action: "This is a serious offense. The officer must issue a charge sheet. You may be arrested and taken to court. Do not attempt to settle on the spot. Request to contact a lawyer immediately.",
    law_version: "2024",
  },
  {
    id: "no-license",
    name: "Driving Without a License",
    aliases: ["unlicensed driving", "no driver's license", "without license"],
    description: "Driving a motor vehicle on a road without holding a valid driving license authorizing you to drive that class of vehicle.",
    category: "license-documents",
    severity: "minor",
    citation: "Traffic Act Cap 403, Section 30",
    act: "Traffic Act Cap 403",
    section: "Section 30",
    min_fine: 1000,
    max_fine: 10000,
    max_imprisonment: null,
    course_of_action: "The officer may issue a charge sheet. You may be required to produce your license at a police station within 14 days. Do not pay on the spot.",
    law_version: "2024",
  },
  {
    id: "no-insurance",
    name: "Driving Without Insurance",
    aliases: ["uninsured vehicle", "no insurance cover", "driving uninsured"],
    description: "Using or causing or permitting any other person to use a motor vehicle on a road without a policy of insurance in respect of third-party risks.",
    category: "license-documents",
    severity: "serious",
    citation: "Traffic Act Cap 403, Section 60",
    act: "Traffic Act Cap 403",
    section: "Section 60",
    min_fine: 10000,
    max_fine: 50000,
    max_imprisonment: "6 months",
    course_of_action: "The officer shall issue a charge sheet. This is a serious offense with potential imprisonment. Do not attempt to settle on the spot. Contact a lawyer.",
    law_version: "2024",
  },
  {
    id: "bald-tires",
    name: "Using Vehicle with Defective Tires",
    aliases: ["bald tires", "worn out tires", "defective tyres", "smooth tires"],
    description: "Using or causing to be used on a road a motor vehicle or trailer with tires that are defective, worn beyond legal limits, or improperly inflated.",
    category: "vehicle-condition",
    severity: "minor",
    citation: "Traffic Act Cap 403, Section 59",
    act: "Traffic Act Cap 403",
    section: "Section 59",
    min_fine: 500,
    max_fine: 3000,
    max_imprisonment: null,
    course_of_action: "The officer may issue a charge sheet. You may also be issued a defect notification requiring repair within a specified period. Do not pay on the spot.",
    law_version: "2024",
  },
  {
    id: "broken-lights",
    name: "Driving Without Proper Lights",
    aliases: ["broken headlights", "no tail lights", "defective lights", "no lights at night"],
    description: "Driving a motor vehicle on a road during the hours of darkness or in adverse weather conditions without the required lighting equipment being in good working order.",
    category: "vehicle-condition",
    severity: "minor",
    citation: "Traffic Act Cap 403, Section 58",
    act: "Traffic Act Cap 403",
    section: "Section 58",
    min_fine: 500,
    max_fine: 2000,
    max_imprisonment: null,
    course_of_action: "The officer may issue a charge sheet or a defect notification. Fix the defect promptly. Do not pay on the spot.",
    law_version: "2024",
  },
  {
    id: "overtaking-yellow-line",
    name: "Overtaking on a Yellow Line",
    aliases: ["overtaking yellow line", "crossing yellow line", "yellow line overtake", "overtaking on yellow"],
    description: "Overtaking or attempting to overtake another vehicle where there is a solid yellow line painted on the roadway indicating no overtaking.",
    category: "traffic-rules",
    severity: "minor",
    citation: "Traffic Act Cap 403, Section 52",
    act: "Traffic Act Cap 403",
    section: "Section 52",
    min_fine: 1000,
    max_fine: 5000,
    max_imprisonment: null,
    course_of_action: "The officer may issue a charge sheet. Do not pay on the spot. If you believe the overtaking was lawful and safe, you may contest in court.",
    law_version: "2024",
  },
  {
    id: "running-red-light",
    name: "Ignoring Traffic Light Signals",
    aliases: ["running red light", "jumping traffic lights", "disobeying traffic lights", "red light violation"],
    description: "Driving past a red traffic light or failing to obey traffic light signals at an intersection or pedestrian crossing.",
    category: "traffic-rules",
    severity: "minor",
    citation: "Traffic Act Cap 403, Section 52",
    act: "Traffic Act Cap 403",
    section: "Section 52",
    min_fine: 1000,
    max_fine: 5000,
    max_imprisonment: null,
    course_of_action: "The officer may issue a charge sheet. Do not pay on the spot. If the traffic light was malfunctioning, note this for your defense.",
    law_version: "2024",
  },
  {
    id: "illegal-parking",
    name: "Illegal Parking",
    aliases: ["wrong parking", "parking in prohibited area", "double parking", "obstructive parking"],
    description: "Parking a motor vehicle in a prohibited area, on a yellow line, on a pedestrian crossing, or in a manner that obstructs traffic or access.",
    category: "parking-loading",
    severity: "minor",
    citation: "Traffic Act Cap 403, Section 53",
    act: "Traffic Act Cap 403",
    section: "Section 53",
    min_fine: 500,
    max_fine: 2000,
    max_imprisonment: null,
    course_of_action: "The officer may issue a parking ticket or charge sheet. Do not pay on the spot. Parking fines can often be paid at the local county government offices or via designated mobile payment channels.",
    law_version: "2024",
  },
  {
    id: "overloading-passengers",
    name: "Overloading with Passengers",
    aliases: ["excess passengers", "overloading vehicle", "carrying excess", "overcrowding vehicle"],
    description: "Driving a motor vehicle carrying more passengers than the licensed carrying capacity of the vehicle.",
    category: "parking-loading",
    severity: "serious",
    citation: "Traffic Act Cap 403, Section 56",
    act: "Traffic Act Cap 403",
    section: "Section 56",
    min_fine: 5000,
    max_fine: 20000,
    max_imprisonment: null,
    course_of_action: "The officer may issue a charge sheet and may prohibit the vehicle from continuing until the excess passengers are removed. Do not pay on the spot.",
    law_version: "2024",
  },
  {
    id: "dui",
    name: "Driving Under the Influence of Alcohol",
    aliases: ["DUI", "drunk driving", "drink driving", "driving while intoxicated", "alcohol impaired driving"],
    description: "Driving or attempting to drive a motor vehicle on a road while under the influence of alcohol to such an extent as to be incapable of having proper control of the vehicle.",
    category: "alcohol-drugs",
    severity: "felony",
    citation: "Traffic Act Cap 403, Section 44(1)",
    act: "Traffic Act Cap 403",
    section: "Section 44(1)",
    min_fine: 100000,
    max_fine: 200000,
    max_imprisonment: "3 years",
    course_of_action: "YOU MAY BE ARRESTED. This is a criminal offense. The officer is required to take you for a breathalyzer or blood test. Do NOT attempt to settle on the spot. You have the right to remain silent and to contact a lawyer immediately. You may also be disqualified from driving.",
    law_version: "2024",
  },
  {
    id: "dui-drugs",
    name: "Driving Under the Influence of Drugs",
    aliases: ["driving while on drugs", "drug impaired driving", "drunk on drugs"],
    description: "Driving or attempting to drive a motor vehicle on a road while under the influence of drugs (including narcotics or prescribed medication that impairs ability) to such an extent as to be incapable of having proper control of the vehicle.",
    category: "alcohol-drugs",
    severity: "felony",
    citation: "Traffic Act Cap 403, Section 44(1)",
    act: "Traffic Act Cap 403",
    section: "Section 44(1)",
    min_fine: 100000,
    max_fine: 200000,
    max_imprisonment: "3 years",
    course_of_action: "YOU MAY BE ARRESTED. This is a criminal offense. Do NOT attempt to settle on the spot. You have the right to remain silent and to contact a lawyer immediately. A medical examination may be required.",
    law_version: "2024",
  },
];

async function seed() {
  console.log("Seeding offenses...");

  for (const o of sampleOffenses) {
    await query(
      `INSERT INTO offenses (id, name, aliases, description, category, severity, citation, act, section, min_fine, max_fine, max_imprisonment, course_of_action, law_version)
       VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
       ON CONFLICT (id) DO UPDATE SET
         name = EXCLUDED.name, aliases = EXCLUDED.aliases, description = EXCLUDED.description,
         category = EXCLUDED.category, severity = EXCLUDED.severity, citation = EXCLUDED.citation,
         act = EXCLUDED.act, section = EXCLUDED.section, min_fine = EXCLUDED.min_fine,
         max_fine = EXCLUDED.max_fine, max_imprisonment = EXCLUDED.max_imprisonment,
         course_of_action = EXCLUDED.course_of_action, law_version = EXCLUDED.law_version,
         updated_at = NOW()`,
      [o.id, o.name, o.aliases, o.description, o.category, o.severity, o.citation, o.act, o.section, o.min_fine, o.max_fine, o.max_imprisonment, o.course_of_action, o.law_version]
    );
  }

  await query("UPDATE status SET total_offenses = $1, last_updated = NOW() WHERE id = 1", [sampleOffenses.length]);
  console.log(`Seeded ${sampleOffenses.length} offenses`);
  process.exit(0);
}

seed().catch((err) => {
  console.error("Seed failed:", err);
  process.exit(1);
});
